server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Bigdata123
    url: jdbc:mysql://localhost:3306/test_hb?characterEncoding=UTF-8&useSSL=false
  jpa:
    properties:
      hibernate:
        search:
#          model_mapping: org.example.config.CustomSearchMappingFactory
          default:
            directory_provider: filesystem
            indexBase: D:\\index
    show-sql: on


